services:
  - type: web
    name: liqs_btc
    env: python
    buildCommand: |
    pip install -r requirements.txt
    playwright install
    startCommand: "python telegram_bot.py"
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
    plan: free
    autoDeploy: false
