services:
  - type: web
    name: liqs_btc
    env: python
    buildCommand: ./render-build.sh
    startCommand: python telegram_bot.py
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
    plan: free
    autoDeploy: false
